import dataclasses
import sys
from typing import Generator

width, height = 864, 486
minChunk = 8

@dataclasses.dataclass
class Pixel:
  r: int
  g: int
  b: int
  def __post_init__(self) -> None:
    assert 0 <= self.r < 256
    assert 0 <= self.g < 256
    assert 0 <= self.b < 256
  def u16(self) -> int:
    r5, g6, b5 = self.r >> 3, self.g >> 2, self.b >> 3
    return (r5 << 11) | (g6 << 5) | b5

def genPixels() -> Generator[Pixel, None, None]:
  while buf := sys.stdin.read(3):
    r, g, b = [int(b) for b in buf]
    yield Pixel(r, g, b)

def genRows() -> Generator[list[Pixel], None, None]:
  row: list[Pixel] = []
  for p in genPixels():
    row.append(p)
    if len(row) == 864:
      yield row
      row = []

class Cmd: pass

class Pixels(Cmd):
  vals: list[Pixel]

class Repeat(Cmd):
  val: Pixel
  count: int

class Nop(Cmd):
  pass

def genCompressedRows() -> Generator[list[Cmd], None, None]:
  for row in genRows():
    crow: list[Cmd] = []
    prev = None
    rep = 0
    for pix in row:
      pass

    yield crow
    # while len(crow) < (minChunk // 2):
    #   crow.append(Nop())
    # i = 1
    # while len(crow) < minChunk:
    #   crow.insert(i, Nop())
    #   i += 2


name = sys.argv[1]
LB, RB = "{}"
size = 864 * 486
print("// Generated by 'hstxpixels.py'")
print("#include \"HSTXPixels.h\"")
print(f"constexpr uint32_t {name}U32s[{size}] {LB}")
print(f"{RB};")
print(f"constexpr auto {name} = HSTXPixels<{width}, {height}>::make<10>({name}U32s);")
